spring.datasource.url=${QUEUE_DB_URL:jdbc:postgresql://localhost:5432/queuedb}
spring.datasource.username=${QUEUE_DB_USERNAME:queuedb}
spring.datasource.password=${QUEUE_DB_PASSWORD:queuedb}

security.jwt.enforce=false
